name: files_cache
description: Package desenvolvida para salvar arquivos temporários na memória de dispositivos em aplicações dart e flutter
version: 1.0.3
homepage: https://github.com/Suebersson/files_cache.git
repository: https://github.com/Suebersson/files_cache

# Comandos para atulizar o repositório no github
# git init
# git add .
# git commit -m "name commit"
# git remote add origin https://github.com/Suebersson/files_cache.git
# git pull origin main
# git push -u origin main

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  dart_dev_utils: ^1.1.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
